version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: syednurjim/php-auto-instrument:stage
    container_name: laravel_test_project
    # volumes:
    #   - /home/zim/code/project-fly_eyes/laravel_crud/test-project:/var/www
    networks:
      - app-network
    #   - signoz-net
    depends_on:
      - db
    environment:
      # === Laravel OpenTelemetry Configuration ===
      - OTEL_SERVICE_NAME=Laravel-Instrumentation-Nginx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://10.104.10.140:44318/v1/traces
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.104.10.140:44318/v1/traces
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://10.104.10.140:44318/v1/logs
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_LOG_LEVEL=info
      # - OTEL_LOG_LEVEL=none  # uncomment to silence logs
      - OTEL_PROPAGATORS=baggage,tracecontext
      - OTEL_ENABLED=true

  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
    #   - /home/zim/code/project-fly_eyes/laravel_crud/test-project:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: php-postgres
    environment:
      POSTGRES_DB: test_crud
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
#   signoz-net:
#     external: true

volumes:
  dbdata:
